# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m flask run
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: "1"
    volumes:
      - .:/app
